//
//  PizzaDeliveryWidget.swift
//  Generated by flutter_activity_kit
//

import ActivityKit
import WidgetKit
import SwiftUI

// MARK: - Activity Attributes (Static & Dynamic State)
public struct PizzaDeliveryAttributes: ActivityAttributes {
    public struct ContentState: Codable, Hashable {
        // Dynamic state updated from Flutter
        public var title: String
        public var message: String
        public var progress: Double // 0.0 to 1.0
        public var status: String
        public var timestamp: Date?
        public var customData: [String: String]?

        public init(
            title: String,
            message: String,
            progress: Double = 0.0,
            status: String = "Active",
            timestamp: Date? = nil,
            customData: [String: String]? = nil
        ) {
            self.title = title
            self.message = message
            self.progress = progress
            self.status = status
            self.timestamp = timestamp
            self.customData = customData
        }
    }

    // Static data initialized when activity starts
    public var activityId: String
    public var category: String
    public var creationDate: Date

    public init(activityId: String, category: String = "default", creationDate: Date = Date()) {
        self.activityId = activityId
        self.category = category
        self.creationDate = creationDate
    }
}

// MARK: - Widget Definition
@available(iOS 16.1, *)
public struct PizzaDeliveryWidget: Widget {
    public var body: some WidgetConfiguration {
        ActivityConfiguration(for: PizzaDeliveryAttributes.self) { context in
            // MARK: Lock Screen & Home Screen Banner
            LockScreenLiveActivityView(context: context)
                .activityBackgroundTint(Color.black.opacity(0.85))
                .activitySystemActionForegroundColor(Color.white)
        } dynamicIsland: { context in
            // MARK: Dynamic Island
            DynamicIsland {
                // Expanded Leading
                DynamicIslandExpandedRegion(.leading) {
                    HStack(spacing: 6) {
                        Image(systemName: "bolt.fill")
                            .foregroundColor(.cyan)
                        Text(context.state.status)
                            .font(.caption2)
                            .fontWeight(.semibold)
                            .foregroundColor(.white)
                    }
                    .padding(.leading, 8)
                }

                // Expanded Trailing
                DynamicIslandExpandedRegion(.trailing) {
                    Text("\(Int(context.state.progress * 100))%")
                        .font(.caption)
                        .fontWeight(.bold)
                        .foregroundColor(.green)
                        .padding(.trailing, 8)
                }

                // Expanded Center / Bottom
                DynamicIslandExpandedRegion(.bottom) {
                    VStack(alignment: .leading, spacing: 6) {
                        Text(context.state.title)
                            .font(.headline)
                            .foregroundColor(.white)
                        Text(context.state.message)
                            .font(.subheadline)
                            .foregroundColor(.gray)

                        // Progress bar
                        ProgressView(value: context.state.progress, total: 1.0)
                            .tint(.cyan)
                    }
                    .padding(.horizontal, 10)
                    .padding(.bottom, 8)
                }
            } compactLeading: {
                // Compact Leading Pill
                HStack(spacing: 4) {
                    Image(systemName: "bolt.fill")
                        .foregroundColor(.cyan)
                    Text(context.state.status)
                        .font(.caption2)
                        .fontWeight(.semibold)
                }
            } compactTrailing: {
                // Compact Trailing Pill
                Text("\(Int(context.state.progress * 100))%")
                    .font(.caption2)
                    .fontWeight(.bold)
                    .foregroundColor(.green)
            } minimal: {
                // Minimal Bubble
                Image(systemName: "bolt.fill")
                    .foregroundColor(.cyan)
            }
        }
    }
}

// MARK: - Lock Screen View
@available(iOS 16.1, *)
struct LockScreenLiveActivityView: View {
    let context: ActivityViewContext<PizzaDeliveryAttributes>

    var body: some View {
        VStack(alignment: .leading, spacing: 10) {
            HStack {
                Label(context.state.title, systemImage: "sparkles")
                    .font(.headline)
                    .foregroundColor(.white)
                Spacer()
                Text(context.state.status)
                    .font(.caption)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 4)
                    .background(Capsule().fill(Color.cyan.opacity(0.3)))
                    .foregroundColor(.cyan)
            }

            Text(context.state.message)
                .font(.subheadline)
                .foregroundColor(.white.opacity(0.85))

            ProgressView(value: context.state.progress, total: 1.0)
                .tint(.cyan)
        }
        .padding(16)
        .background(Color.black.opacity(0.8))
    }
}
